#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JS_PATH=$DIR/../assets/js
FILE_LIST="spin.min.js files.utilities.js files.state.js files.template.js files.grid.js files.tree.js files.row.js files.paginator.js files.pathway.js files.app.js files.attachments.app.js files.uploader.js files.copymove.js"
OUTPUT_FILE=files.min.js

UPLOADER_LIST="plupload/moxie.js plupload/plupload.dev.js plupload/plupload.queue.js"
UPLOADER_OUTPUT_FILE=uploader.min.js

cd $JS_PATH
cat $FILE_LIST | uglifyjs -o $OUTPUT_FILE

cat $UPLOADER_LIST | uglifyjs -o $UPLOADER_OUTPUT_FILE
