#!/usr/bin/env bash

# Location of the gruntfile in the build-scripts repo. You only need to change these two variables
GRUNTFOLDER="joomlatools"
GRUNTFILE="joomlatools-framework-files.js"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPTS_DIR="$(dirname $(dirname $(dirname "$DIR")))/build-scripts"

if [ ! -d "$SCRIPTS_DIR" ]; then
    echo "cloning build-scripts into Projects folder..."
    git clone git@github.com:joomlatools/build-scripts.git "$SCRIPTS_DIR"
fi

source $SCRIPTS_DIR/grunt/run