#!/bin/bash

LESSC_BIN=lessc
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INPUT_PATH=$DIR/../code/media/koowa/com_files/less
FW_PATH=$DIR/../../koowa/code/media/koowa/com_koowa/less
FW_PATH_ALT=$DIR/../../joomlatools-framework/code/media/koowa/com_koowa/less
OUTPUT_PATH=$DIR/../code/media/koowa/com_files/css
FILES=('files')

while [ ! -d "$FW_PATH" ]
do
  if [ -d "$FW_PATH_ALT" ]; then
    FW_PATH=$FW_PATH_ALT
    break
  fi
  echo "${FW_PATH} doesn't exist!"
  read -p "Enter the root directory for the koowa framework git checkout, or hit enter to skip:
" FW_PROMPT
  echo "You entered: $FW_PROMPT"
  if [ "$FW_PROMPT" = '' ]; then
    break
  fi
  FW_PATH=$FW_PROMPT/code/media/koowa/com_koowa/less
done

for FILE in "${FILES[@]}"
do
  $LESSC_BIN --include-path="$FW_PATH:$FILES_PATH" --verbose $INPUT_PATH/$FILE.less $OUTPUT_PATH/$FILE.css -compress
done