#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JS_PATH=../code/media/koowa/com_files/js
FILE_LIST="spin.min.js files.utilities.js files.state.js files.template.js files.grid.js files.tree.js files.row.js files.paginator.js files.pathway.js files.app.js"
OUTPUT_FILE=files.min.js

cd $DIR/$JS_PATH
cat $FILE_LIST | uglifyjs -o $OUTPUT_FILE 